tasks:
  - before: >
        mkdir -p ~/.ssh &&
        [[ ! -z $GP_SSH_SIGNING_KEY  ]] &&
        echo $GP_SSH_SIGNING_KEY > ~/.ssh/id_rsa.pub &&
        chmod 644 ~/.ssh/id_rsa.pub &&
        [[ ! -z $GP_SSH_SIGNING_PRIVKEY  ]] &&
        echo $GP_SSH_SIGNING_PRIVKEY | base64 -d > ~/.ssh/id_rsa &&
        chmod 600 ~/.ssh/id_rsa
  - name: Python environment
    command: |
      apt-get install python3-flask -y
      pip3 install -r requirements.txt
      python -m venv venv
      source ./venv/bin/activate
      export FLASK_APP=./app/vuln_app.py
      export FLASK_ENV=development
      flask --debug run

ports:
  - name: flask-app
    description: The flask web app 
    port: 5000
    visibility: private
  - name: slides preview 
    description: Preview window of presentation
    port: 5500
    visibility: private
    onOpen: open-browser

gitConfig:
    gpg.format: ssh
    commit.gpgsign: "true"
    user.signingkey: ~/.ssh/id_rsa.pub

vscode:
    extensions:
        - marp-team.marp-vscode
        - ms-python.python
        - mhutchie.git-graph
        - ritwickdey.LiveServer